name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: production
    concurrency: production

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: "Install Deps"
        run: yarn
      - name: "Compile Pages"
        run: yarn deploy
      - name: "Deeeploy!"
        run: |
          git config --global user.email "Cocacola5010mc@gmail.com"
          git config --global user.name "Pipeline Runner, Caleb Owens"
          echo 'www.calebowens.com' > ./dist/CNAME
          yarn gh-pages -d dist -r https://${{ secrets.USER_TOKEN }}@github.com/calebowens/calebowens.git
